# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('visit', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=30)),
                ('hiv', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='forms/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='select your Gender', max_length=30)),
                ('position', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Volunteer', 'Volunteer')], default='select your position', max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('pic', models.ImageField(blank=True, default='no profile pic', upload_to='avatar/')),
                ('work_id', models.CharField(default='No work ID', max_length=30)),
                ('hospital_name', models.CharField(default='Health-e-net attendant', max_length=54)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='original_image',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='health_app.Profile'),
        ),
    ]
