# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_id',
            field=models.CharField(max_length=30),
        ),
    ]
